// <auto-generated />
namespace SimpleCms.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class Updates : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Updates));
        
        string IMigrationMetadata.Id
        {
            get { return "201406230232556_Updates"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
